$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  data:
    type: object
    properties:
      file:
        type: string
      mutant_file:
        type: string
    required:
      - file
  normality:
    type: object
    properties:
      test:
        type: string
    required:
      - test
  variables:
    type: object
    preperties:
      notselected:
        type: string
    required:
      - notselected
