$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  data:
    type: object
    properties:
      file:
        type: string
    required:
      - file
